#!/bin/sh

book="$1"
chapter="$2"
verse="$3"

# HELP
help() {
	while IFS= read -r line; do
		printf "%s\n" "$line"
	done <<-EOF
	Usage:
	  ${0##*/} BOOK CHAPTER VERSE
	  ${0##*/} -r
	  ${0##*/} -i BOOK CHAPTER VERSE
	Options:
	  -r Get random verse
	  -i Write verse to image
	EOF
}

# MENU
menu_line_even () {
	# displays an even (cyan) line of a menu line with $2 as an indicator in [] and $1 as the option
	printf "\033[1;34m[\033[1;36m%s\033[1;34m] \033[1;36m%s\033[0m\n" "$2" "$1"
}

menu_line_odd() {
	# displays an odd (yellow) line of a menu line with $2 as an indicator in [] and $1 as the option
	printf "\033[1;34m[\033[1;33m%s\033[1;34m] \033[1;33m%s\033[0m\n" "$2" "$1"
}

prompt () {
	# prompts the user with message in $1-2 ($1 in blue, $2 in magenta) and saves the input to the variables in $REPLY and $REPLY2
	printf "\033[1;34m%s\033[1;34m: \033[0m" "$1"
}

menu_line_alternate() {
	menu_line_parity=${menu_line_parity:-0}
	if [ "$menu_line_parity" -eq 0 ]; then
		menu_line_odd "$1" "$2"
		menu_line_parity=1
	else
		menu_line_even "$1" "$2"
		menu_line_parity=0
	fi
}

search(){
  bible=$(curl -s "https://bible-api.com/$book%20$chapter:$verse" | jq .text)
  printf '%s\n' "$book $chapter:$verse"
  echo "$bible"
}

random(){
	random=$(curl -s "https://bible-api.com/?random=verse")
	reference=$(printf '%s' "$random" | jq .reference)
	text=$(printf '%s' "$random" | jq .text)
	tput clear
	printf '%s\n\n' "$reference"
	echo "$text"
}

toimg(){
   if [ -z "$1" ]; then
      prompt "Enter Book,Chapter,Verse(ex = John 3 16)"
	  read -r book chapter verse
	  verse_to_img=$(search)
      echo "$verse_to_img" | python3 bibleonimage.py
   else
   	  verse_to_img=$(search)
	  echo "$verse_to_img" | python3 bibleonimage.py
   fi
}

while getopts "r:ih" arg; do
    case "$arg" in
    r)
        random
		exit 0
        ;;
    i)
        toimg "$book" "$chapter" "$verse"
		exit 0
        ;;
    h)
		help
		exit 1
        ;;
	*)
		help
		exit 1
		;;
    esac
done

if [ -z "$*" ]; then
   prompt "Enter Book,Chapter,Verse(ex = John 3 16)"         
   read -r book chapter verse
   search
else
   search
fi

