#!/bin/sh

# HELP
help() {
cat << EOF
Usage:
  ${0##*/} [BOOK CHAPTER VERSE]
  ${0##*/} [-i [BOOK CHAPTER VERSE]]
  ${0##*/} [-r -i] | [-i -r]
  Options:
	-r : Get random verse
	-i : Write verse to image
EOF
}

# FUNCTIONS
search(){
	bible=$(curl -s "https://bible-api.com/$book%20$chapter:$verse" | jq .text)
	printf '%s\n' "$book $chapter:$verse"
	echo "$bible"
}

random(){
	random=$(curl -s "https://bible-api.com/?random=verse")
	reference=$(printf '%s' "$random" | jq .reference)
	text=$(printf '%s' "$random" | jq .text)
	printf '%s\n' "$reference"
	echo "$text"
}

toimg(){
	verse_to_img=$(search)
	echo "$verse_to_img" | python3 verseonimage.py
}

while getopts "rih" arg; do
	case "$arg" in
	r)
		for args in "$@"
		do
			[ "-i" = "$args" ] && verse_to_img=$(random) && echo "$verse_to_img" | python3 verseonimage.py && exit 0
		done
		random
		exit 0
		;;
	i)
		to_img=1
		;;
	h)
		help
		exit 1
		;;
	*)
		help
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

book="$1"
chapter="$2"
verse="$3"

if [ -z "$book" ] || [ -z "$chapter" ] || [ -z "$verse" ]; then
	printf "\033[1;37m%s\033[1;37m: \033[0m" "Enter Book,Chapter,Verse(ex = John 3 16)"
	read -r book chapter verse
fi

if [ "$to_img" = 1 ];then
	toimg
else
	search
fi
